config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'tasks#index'
  # resources :tasks, except: %i[destroy] do
  resources :tasks  do
    delete :index, on: :collection, action: :delete
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task

  validates :contents, presence: true, length: { maximum: 256 }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :comments, dependent: :destroy

  attr_accessor :statuses, :priorities

  enum priority: { normal: 0, low: -1, high: 1 }, _prefix: true
  enum status: { todo: 0, doing: 1, done: 2 }, _prefix: true

  validates :title, presence: true, length: { maximum: 256 }
  validates :status, presence: true
  validate :not_before_today, on: :create

  scope :title_like, ->(title) { where('title like ?', "%#{title}%") if title.present? }
  scope :description_like, ->(description) { where('description like ?', "%#{description}%") if description.present? }
  scope :status_in, ->(statuses) { where(status: statuses) if statuses.present?}
  scope :priority_in, ->(priorities) { where(priority: priorities) if priorities.present?}

  def search
    Task.title_like(title).description_like(description).status_in(statuses).priority_in(priorities)
  end

  def not_before_today
    errors.add(:due_date, :not_before_today) if due_date.present? && due_date < Date.today
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :set_task, only: %i[new create edit update destroy]
  before_action :set_comment, only: %i[edit update destroy]

  def new
    @comment = @task.comments.new
  end

  def create
    @comment = @task.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to tasks_path, notice: t('views.notice.success.register', model: Comment.model_name.human) }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to tasks_path, notice: t('views.notice.success.update', model: Comment.model_name.human) }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: t('views.notice.success.destroy', model: Comment.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

def comment_params
    params.require(:comment).permit(:contents)
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @q = Task.ransack(params[:q])
    # デフォルトソート順を設定する場合
    # @q.sorts = 'priority desc' if @q.sorts.empty? 
    @tasks = @q.result(distinct: true).page(params[:page]).includes(:comments)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show; end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit; end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: t('views.notice.success.register', model: Task.model_name.human) }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: t('views.notice.success.update', model: Task.model_name.human) }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks
  # DELETE /tasks.json
  def delete
    Task.destroy(params[:ids].keys)
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: t('views.notice.success.destroy', model: Task.model_name.human) }
      format.json { head :no_content }
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: t('views.notice.success.destroy', model: Task.model_name.human) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    # 許可する項目だけを記載する
    params.fetch(:task, {}).permit(:title, :description, :status, :priority, :due_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
# frozen_string_literal: true

module TasksHelper
  def sort_items
    select_hash = []
    select_hash << ['ID(昇順)', 'id asc']
    select_hash << ['ID(降順)', 'id desc']
    select_hash << ['タイトル(昇順)', 'title asc']
    select_hash << ['タイトル(降順)', 'title desc']
    select_hash << ['優先度(昇順)', 'priority asc']
    select_hash << ['優先度(降順)', 'priority desc']
  end
end

app/views/comments/_form.html.slim
= form_for [@task, @comment] do |f|
  - if @comment.errors.any?
    #error_explanation
      h2 = "#{pluralize(@comment.errors.count, "error")} prohibited this comment from being saved:"
      ul
        - @comment.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :contents
    = f.text_field :contents, class: "form-control"

  .actions = f.button class: "btn btn-primary"

app/views/comments/_index.html.slim
.modal-dialog.modal-lg role="document" 
  .modal-content
    .modal-header
      h5#exampleModalLabel.modal-title コメント
      button.close aria-label="Close" data-dismiss="modal" type="button" 
        span aria-hidden="true"  ×
    .modal-body
      - task.comments.each do |comment|
        .d-flex.justify-content-between
          = comment.contents
          .
            .mx-1.d-inline = link_to image_tag('edit.png'), edit_task_comment_path(task, comment), title: "編集", data: {toggle: 'tooltip', placement: 'bottom'}
            .mx-1.d-inline = link_to image_tag('delete.png'), task_comment_path(task, comment), title: "削除", data: { confirm: t('views.confirm.destroy'), toggle: 'tooltip', placement: 'bottom' }, method: :delete
    .modal-footer
      button.btn.btn-secondary data-dismiss="modal" type="button"  Close
      = link_to t('button.add'), new_task_comment_path(task),  class: 'btn btn-primary m-1'

app/views/comments/edit.html.slim
.taskul-title-area
  p.h2.d-inline コメント編集

== render 'form'

= link_to t('button.back'), tasks_path

app/views/comments/new.html.slim
.taskul-title-area
  p.h2.d-inline コメント登録

== render 'form'

= link_to t('button.back'), tasks_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title TaskulSlim
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    javascript:
      I18n.defaultLocale = "#{I18n.default_locale}";
      I18n.locale = "#{I18n.locale}";
      I18n.fallbacks = true;
  body

    /! 固定ヘッダ
    .sticky-top
      nav.navbar.navbar-dark.navbar-expand-lg.taskul-nav-color
        a.navbar-brand href="/"  Taskul
        /! レスポンシブデザイン用に画面サイズが小さくなったらdata-targetのブロックを隠し、右側にメニューを表示する
        button.navbar-toggler aria-controls="navbarSupportedContent" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarSupportedContent" data-toggle="collapse" type="button" 
          span.navbar-toggler-icon
        /! Bootstrapのドロップダウンメニューを利用。中のテキストは画像にしている
        #navbarSupportedContent.collapse.navbar-collapse
          ul.navbar-nav.ml-auto
            li.nav-item.dropdown
              a#navbarDropdown.nav-link.dropdown-toggle aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" href="#" role="button" 
                /! イメージを直接表示する場合
                = image_tag('user.png') 
                /! イメージもCSS化する場合は以下のような感じ　
                /! <div id="taskul-user" class="img-fluid"></div
              .dropdown-menu.dropdown-menu-right aria-labelledby="navbarDropdown" 
                a.dropdown-item href="#"  プロフィール
                a.dropdown-item href="#"  アカウント管理
                .dropdown-divider
                a.dropdown-item href="#"  Something else here

    .container-fluid
      = yield

app/views/tasks/_form.html.slim
= form_for @task do |f|
  - if @task.errors.any?
    #error_explanation
      h2 = "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @task.errors.full_messages.each do |message|
          li = message

  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :description
    = f.text_area :description, class: "form-control"
  .form-group
    = f.label :priority
    = f.select :priority, Task.priorities.keys.to_a, {},  class: "custom-select"
  .form-group
    = f.label :status
    = f.select :status, Task.statuses.keys.to_a, {},  class: "custom-select"
  .form-group
    = f.label :due_date
    = f.date_field :due_date, class: "form-control"

  .actions = f.button class: "btn btn-primary"

app/views/tasks/_search.html.slim
.modal.fade id="search-modal" aria-hidden="true" role="dialog" tabindex="-1" 
  .modal-dialog role="document" 
    .modal-content
      .modal-header
        h5.modal-title 詳細検索
        button.close aria-label="Close" data-dismiss="modal" type="button" 
          span aria-hidden="true"  ×
      = search_form_for(@q, url:tasks_path) do |f|
        .modal-body
            .form-group
              = f.label :title
              = f.search_field :title_cont, class: "form-control"
            .form-group
              = f.label :description
              = f.search_field :description_cont, class: "form-control"
            .form-group
              = f.label "コメント"
              = f.search_field :comments_contents_cont, class: "form-control"
            .form-group
              = f.label '並び順'
              / sort_itemsは自作ヘルパーメソッド
              = select_tag 'q[s]', options_for_select(sort_items), class: 'custom-select'
        .modal-footer
          button.btn.btn-secondary data-dismiss="modal" type="button"  Close
          = f.submit class: 'btn btn-primary m-1'

app/views/tasks/edit.html.slim
.taskul-title-area
  p.h2.d-inline タスク編集

== render 'form'

=> link_to t('button.show'), @task
'|
=< link_to t('button.back'), tasks_path

app/views/tasks/index.html.slim
.row
  p.h2.col-2.mt-2 タスク

/ 通知エリア
- if flash[:notice]
  div#notice.alert.alert-success = notice

/ ボタンエリア
.taskul-title-area.d-flex.justify-content-start.align-items-center
  /! TODO: 反転もできるようにしたい
  .mr-auto
    button.btn.btn-info.btn-sm.m-1 未着手
    button.btn.btn-warning.btn-sm.m-1 着手
    button.btn.btn-success.btn-sm.m-1 完了
  .ml-auto
    button#search-detail-btn.btn.btn-secondary.m-1 data-target="#search-modal" data-toggle="modal" type="button" = t('button.search_detail') 
    button#delete-btn.btn.btn-danger.m-1 = t('button.destroy')
    = link_to t('button.new'), new_task_path, class: 'btn btn-primary m-1'

/ 検索モーダル
== render 'search'

= form_tag(tasks_path) do
  / ページネーション
  p.text-center.mb-0.small.text-secondary = page_entries_info @tasks
  = paginate @tasks

  / タスクの一覧
  .row
    - @tasks.each_with_index do |task, i|
      .col-6.col-md-4.col-xl-3.mb-4
        .card.h-100
          .card-header.taskul-color-card.text-white.text-truncate = task.title
          .taskul-card-image-frame
            = link_to image_tag("card#{(1..5).to_a.sample}.jpg", class: 'card-img-top taskul-card-img'), task
            button.btn.btn-link data-target="#comment-modal-#{task.id}" data-toggle="modal" type="button" 
              / = image_tag("fukidashi.png", class: 'taskul-comment')
              h5
                span.badge.badge-pill.badge-success.px-3.py-2 = task.comments.size

          .card-body
            p.card-text = task.description
          .d-flex.justify-content-center.mb-2
            .badge.badge-success.mr-2.align-bottom.p-2 = task.priority
            .badge.badge-info.mr-2.align-bottom.p-2 = task.status

          / TODO:ここで裏ではページ内タスク分データ保持しちゃってるので、本当は押された時にajaxで取りに行った方がいいんだろうな
          / TODO:その関係か、画面遷移時に一瞬モーダルが表示されたりしちゃう
          .modal.fade id="comment-modal-#{task.id}" aria-hidden="true" role="dialog" tabindex="-1" 
            == render 'comments/index', task: task 

          .card-footer.d-flex.justify-content-center
            .mx-3 = link_to image_tag('detail.png'), task, title: "詳細", data: {toggle: 'tooltip', placement: 'bottom'}
            .mx-3 = link_to image_tag('edit.png'), edit_task_path(task), title: "編集", data: {toggle: 'tooltip', placement: 'bottom'}
            .mx-3 = link_to image_tag('delete.png'), task, title: "削除", data: { confirm: t('views.confirm.destroy'), toggle: 'tooltip', placement: 'bottom' }, method: :delete

  / ページネーション
  p.text-center.mb-0.small.text-secondary = page_entries_info @tasks
  = paginate @tasks





  / ★テーブルで一覧を出力する場合
  / .table-responsive
  /   table.table.table-striped
  /     thead
  /       tr
  /         th scope="col" 
  /           input#checkbox-header.styled type="checkbox" 
  /         th = Task.human_attribute_name(:title)
  /         th = Task.human_attribute_name(:priority)
  /         th = Task.human_attribute_name(:status)
  /         th = Task.human_attribute_name(:due_date)
  /         th = Task.human_attribute_name(:created_at)
  /         th = Task.human_attribute_name(:updated_at)
  /         th.px-0 アクション 
  /     tbody
  /       - @tasks.each do |task|
  /         tr
  /           th scope="row" 
  /             = check_box_tag "ids[#{ task.id }]", task.id, false, class: "styled checkbox-list"
  /           td = task.title
  /           td = task.priority
  /           td = task.status
  /           td = task.due_date
  /           td = task.created_at
  /           td = task.updated_at
  /           td.px-0.d-flex
  /             .mx-1 = link_to image_tag('detail.png'), task
  /             .mx-1 = link_to image_tag('edit.png'), edit_task_path(task)
  /             .mx-1 = link_to image_tag('delete.png'), task, data: { confirm: t('view.confirm.destroy') }, method: :delete

app/views/tasks/new.html.slim
.taskul-title-area
  p.h2.d-inline タスク登録

== render 'form'

= link_to t('button.back'), tasks_path

app/views/tasks/show.html.slim
.taskul-title-area
  p.h2.d-inline タスク詳細

- if flash[:notice]
  div#notice.alert.alert-success = notice

= form_for @task do |f|
  .item
    = f.label :title, class: "inline"
    = @task.title
  .item
    = f.label :description, class: "inline"
    = @task.description
  .item
    = f.label :priority, class: "inline"
    = @task.priority
  .item
    = f.label :status, class: "inline"
    = @task.status
  .item
    = f.label :due_date, class: "inline"
    = @task.due_date


=> link_to t('button.edit'), edit_task_path(@task)
'|
=< link_to t('button.back'), tasks_path